sudo: required
service:
 - docker
before_install:
  - docker build -t notepad1979/new1:latest .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push notepad1979/new1:latest
notifications:
 email:
   recipients:
     - nandhakumarta@gmail.com
   on_success: always
   on_failure: always
